# Generated by Django 4.0.3 on 2022-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_food_logo_order_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dish_image',
        ),
        migrations.AddField(
            model_name='food',
            name='dish_image',
            field=models.ImageField(blank=True, upload_to='dishes/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
